services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=DataSource=/app/data/library.db
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - LC_ALL=uk_UA.UTF-8
    volumes:
      - appdata:/app/data


volumes:
  appdata: